build:
	mlton -default-type int64 factorial_accumulator.sml
	mlton -default-type int64 fibonacci_recursive.sml
	mlton -default-type int64 sum_range.sml
	mlton -default-type int64 iterate_increment.sml
	mlton -default-type int64 match_options.sml
	mlton -default-type int64 lookup_tree.sml
	mlton -default-type int64 erase_unused.sml

clean:
	rm -f factorial_accumulator
	rm -f fibonacci_recursive
	rm -f sum_range
	rm -f iterate_increment
	rm -f match_options
	rm -f lookup_tree
	rm -f erase_unused
